#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=19

boot() {
	# check device if in fac mode
	local ft_mode=`cat /proc/xiaoqiang/ft_mode`
	[ "${ft_mode}" -eq "0" ] && exit 0

	# Check if have KF partion
	local line=`cat /proc/mtd |grep KF`	# mtd2: 00010000 00010000 "KF"
	local name=`echo ${line} |awk -F'"' '{print $2}'`	# KF
	local dev=`echo ${line} |awk -F':' '{print $1}'`	# mtd2

	local mtdPtn=`echo ${dev} |grep mtd`
	[ "KF" != "${name}" ] && exit 0
	[ -z "${mtdPtn}" ] && exit 0

	# Fill the partion with random numbers and check nice
	local isAllf=`hexdump /dev/${dev} |grep "ffff ffff"`
	local isAll0=`hexdump /dev/${dev} |grep "0000 0000"`

	while [ -n "${isAllf}" ] || [ -n "${isAll0}" ]
	do
		mtd erase /dev/${dev}
		dd if=/dev/urandom of=/dev/${dev} bs=64k count=1
		isAllf=`hexdump /dev/${dev} |grep "ffff ffff"`
		isAll0=`hexdump /dev/${dev} |grep "0000 0000"`
		echo "Rewrite KF partion!"
	done

	return 0
}
