#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2015 OpenWrt.org

START=60
USE_PROCD=1

BIN=xl2tpd
RUN_D="/var/run/xl2tpd"
PID_F="/var/run/xl2tpd.pid"

start_service() {
	rm -rf "$RUN_D"
	mkdir -p "$RUN_D"

	#not work for ap-mode
	ap_mode=$(uci -q get xiaoqiang.common.NETMODE)
	[ "$ap_mode" = "lanapmode" -o "$ap_mode" = "wifiapmode" -o "$ap_mode" = "whc_re" ] && exit 0

	#no need to start l2tpd service for most users
	vpn_prot=$(uci -q get network.vpn.proto)
	[ "$vpn_prot" == "l2tp" ] || exit 0

	procd_open_instance
	procd_set_param command $BIN -D -l -p "$PID_F"
	procd_set_param respawn
	procd_close_instance
}

stop_service() {
	rm -rf "$RUN_D"
	rm -rf "$PID_F"
}
